name: miki

on: 
  push:
    tags:
    - '*'

jobs:
  miki101:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: miki test nested
      run: git submodule foreach --recursive 'git checkout main && git pull'
    - name: Checkout Submodules
      run: git submodule update --init --recursive
    - uses: ncipollo/release-action@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        ref: 'main'
        submodules: recursive
        fetch-depth: 0
          # - uses: byteever/action-build-zip@master
        #artifacts: "release.tar.gz,foo/*.txt"
        #bodyFile: "body.md"
