name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Checkout Submodules
      run: git submodule update --init --recursive
    - uses: ncipollo/release-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        #artifacts: "release.tar.gz,foo/*.txt"
        #bodyFile: "body.md"
